name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: praqo/countrynfo
          publish_dir: ./build
          user_name: praqo
          user_email: 142553687+praqo@users.noreply.github.com
          publish_branch: gh-pages
